stages:
  - build

build_docker_image_for_tags:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/calcetthon:$CI_COMMIT_TAG --build-arg executable=calcetthon-exe -f docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/calcetthon:$CI_COMMIT_TAG
    - docker rmi $CI_REGISTRY_IMAGE/calcetthon:$CI_COMMIT_TAG
  tags:
    - native
  only:
    - tags