version: '2'
services:
  postgres:
    image: postgres:10.4-alpine
    container_name: calcetthon-postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - base
    environment:
      - POSTGRES_USER=calcetthon
      - POSTGRES_PASSWORD=calcetthon
      - POSTGRES_DB=calcetthon

  pgadmin:
    image: fenglc/pgadmin4:2-python3.6-alpine
    container_name: calcetthon-pgadmin
    links:
      - postgres:postgresql
    depends_on:
      - postgres
    ports:
      - 5050:5050
    networks:
      - base
    environment:
      - DEFAULT_USER=calcetthon@calcetthon.org
      - DEFAULT_PASSWORD=calcetthon

volumes:
  postgres-data:
    driver: local

networks:
  base:
